import "./globals.css"

{/*
1) Home Page: Hero, feature, workout programs, footer.
2) Program page: About the program with features, workout days.
3) Workout page: About the workout features, individual exercises.
*/}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
